/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BannerInput = IDL.Record({
  'title' : IDL.Text,
  'linkUrl' : IDL.Text,
  'order' : IDL.Nat,
  'isActive' : IDL.Bool,
  'image' : ExternalBlob,
  'subtitle' : IDL.Text,
});
export const Banner = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'linkUrl' : IDL.Text,
  'order' : IDL.Nat,
  'isActive' : IDL.Bool,
  'image' : ExternalBlob,
  'subtitle' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const CouponCode = IDL.Text;
export const DiscountType = IDL.Variant({
  'flat' : IDL.Null,
  'percent' : IDL.Null,
});
export const CouponInput = IDL.Record({
  'discountValue' : IDL.Nat,
  'expiresAt' : Timestamp,
  'maxDiscount' : IDL.Nat,
  'code' : CouponCode,
  'discountType' : DiscountType,
  'maxUsage' : IDL.Nat,
  'minOrderValue' : IDL.Nat,
  'isActive' : IDL.Bool,
});
export const Specification = IDL.Record({
  'key' : IDL.Text,
  'value' : IDL.Text,
});
export const ProductInput = IDL.Record({
  'specifications' : IDL.Vec(Specification),
  'originalPrice' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'isFlashDeal' : IDL.Bool,
  'isTrending' : IDL.Bool,
  'images' : IDL.Vec(ExternalBlob),
});
export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'specifications' : IDL.Vec(Specification),
  'originalPrice' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'isFlashDeal' : IDL.Bool,
  'isTrending' : IDL.Bool,
  'images' : IDL.Vec(ExternalBlob),
});
export const ReviewInput = IDL.Record({
  'productId' : ProductId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ReviewId = IDL.Nat;
export const UserId = IDL.Principal;
export const Review = IDL.Record({
  'id' : ReviewId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ApplyCouponResult = IDL.Record({
  'discountAmount' : IDL.Nat,
  'message' : IDL.Text,
  'isValid' : IDL.Bool,
});
export const ReferralCode = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'out_for_delivery' : IDL.Null,
  'ordered' : IDL.Null,
  'delivered' : IDL.Null,
  'packed' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cod' : IDL.Null,
  'upi' : IDL.Null,
  'card' : IDL.Null,
  'split' : IDL.Record({
    'method1' : IDL.Text,
    'method2' : IDL.Text,
    'amount1' : IDL.Nat,
    'amount2' : IDL.Nat,
  }),
  'wallet' : IDL.Null,
});
export const Address = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const TrackingStep = IDL.Record({
  'status' : OrderStatus,
  'note' : IDL.Text,
  'timestamp' : IDL.Opt(Timestamp),
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'userId' : UserId,
  'discountAmount' : IDL.Nat,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalAmount' : IDL.Nat,
  'address' : Address,
  'couponApplied' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
  'trackingSteps' : IDL.Vec(TrackingStep),
});
export const UserProfile = IDL.Record({
  'referralCode' : ReferralCode,
  'preferredLanguage' : IDL.Text,
  'name' : IDL.Text,
  'rewardPoints' : IDL.Nat,
  'email' : IDL.Text,
  'referredBy' : IDL.Opt(ReferralCode),
  'recentlyViewed' : IDL.Vec(ProductId),
  'address' : IDL.Opt(
    IDL.Record({
      'city' : IDL.Text,
      'line1' : IDL.Text,
      'line2' : IDL.Text,
      'state' : IDL.Text,
      'pincode' : IDL.Text,
    })
  ),
  'phone' : IDL.Text,
  'wishlist' : IDL.Vec(ProductId),
});
export const Coupon = IDL.Record({
  'discountValue' : IDL.Nat,
  'expiresAt' : Timestamp,
  'maxDiscount' : IDL.Nat,
  'code' : CouponCode,
  'discountType' : DiscountType,
  'usageCount' : IDL.Nat,
  'maxUsage' : IDL.Nat,
  'minOrderValue' : IDL.Nat,
  'isActive' : IDL.Bool,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Cart = IDL.Record({
  'userId' : UserId,
  'couponApplied' : IDL.Opt(CouponCode),
  'items' : IDL.Vec(CartItem),
});
export const NotificationId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'reward' : IDL.Null,
  'order' : IDL.Null,
  'deal' : IDL.Null,
  'price_drop' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
});
export const PlaceOrderInput = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'discountAmount' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'address' : Address,
  'couponApplied' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
});
export const UserProfileInput = IDL.Record({
  'preferredLanguage' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Opt(
    IDL.Record({
      'city' : IDL.Text,
      'line1' : IDL.Text,
      'line2' : IDL.Text,
      'state' : IDL.Text,
      'pincode' : IDL.Text,
    })
  ),
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBanner' : IDL.Func([BannerInput], [Banner], []),
  'addCoupon' : IDL.Func([CouponInput], [], []),
  'addProduct' : IDL.Func([ProductInput], [Product], []),
  'addReview' : IDL.Func([ReviewInput], [Review], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
  'applyCoupon' : IDL.Func([CouponCode, IDL.Nat], [ApplyCouponResult], []),
  'applyReferralCode' : IDL.Func([ReferralCode], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteBanner' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCoupon' : IDL.Func([CouponCode], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'deleteReview' : IDL.Func([ReviewId], [IDL.Bool], []),
  'generateReferralCode' : IDL.Func([], [ReferralCode], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserId, UserProfile))],
      ['query'],
    ),
  'getAvailableCoupons' : IDL.Func([IDL.Nat], [IDL.Vec(Coupon)], ['query']),
  'getBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
  'getBestCoupon' : IDL.Func([IDL.Nat], [IDL.Opt(Coupon)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFlashDeals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getRecentlyViewed' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'getReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'getRewards' : IDL.Func([], [IDL.Nat], ['query']),
  'getTrendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'placeOrder' : IDL.Func([PlaceOrderInput], [Order], []),
  'redeemRewards' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'removeFromWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileInput], [UserProfile], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'seedSampleData' : IDL.Func([], [IDL.Text], []),
  'sendNotification' : IDL.Func(
      [UserId, NotificationType, IDL.Text, IDL.Text],
      [Notification],
      [],
    ),
  'trackRecentlyViewed' : IDL.Func([ProductId], [], []),
  'updateBanner' : IDL.Func([IDL.Nat, BannerInput], [IDL.Opt(Banner)], []),
  'updateCartItem' : IDL.Func([ProductId, IDL.Nat], [], []),
  'updateCoupon' : IDL.Func([CouponInput], [IDL.Bool], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Opt(Order)], []),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Opt(Product)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BannerInput = IDL.Record({
    'title' : IDL.Text,
    'linkUrl' : IDL.Text,
    'order' : IDL.Nat,
    'isActive' : IDL.Bool,
    'image' : ExternalBlob,
    'subtitle' : IDL.Text,
  });
  const Banner = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'linkUrl' : IDL.Text,
    'order' : IDL.Nat,
    'isActive' : IDL.Bool,
    'image' : ExternalBlob,
    'subtitle' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const CouponCode = IDL.Text;
  const DiscountType = IDL.Variant({ 'flat' : IDL.Null, 'percent' : IDL.Null });
  const CouponInput = IDL.Record({
    'discountValue' : IDL.Nat,
    'expiresAt' : Timestamp,
    'maxDiscount' : IDL.Nat,
    'code' : CouponCode,
    'discountType' : DiscountType,
    'maxUsage' : IDL.Nat,
    'minOrderValue' : IDL.Nat,
    'isActive' : IDL.Bool,
  });
  const Specification = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const ProductInput = IDL.Record({
    'specifications' : IDL.Vec(Specification),
    'originalPrice' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'isFlashDeal' : IDL.Bool,
    'isTrending' : IDL.Bool,
    'images' : IDL.Vec(ExternalBlob),
  });
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'specifications' : IDL.Vec(Specification),
    'originalPrice' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'isFlashDeal' : IDL.Bool,
    'isTrending' : IDL.Bool,
    'images' : IDL.Vec(ExternalBlob),
  });
  const ReviewInput = IDL.Record({
    'productId' : ProductId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ReviewId = IDL.Nat;
  const UserId = IDL.Principal;
  const Review = IDL.Record({
    'id' : ReviewId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'productId' : ProductId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ApplyCouponResult = IDL.Record({
    'discountAmount' : IDL.Nat,
    'message' : IDL.Text,
    'isValid' : IDL.Bool,
  });
  const ReferralCode = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'out_for_delivery' : IDL.Null,
    'ordered' : IDL.Null,
    'delivered' : IDL.Null,
    'packed' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'cod' : IDL.Null,
    'upi' : IDL.Null,
    'card' : IDL.Null,
    'split' : IDL.Record({
      'method1' : IDL.Text,
      'method2' : IDL.Text,
      'amount1' : IDL.Nat,
      'amount2' : IDL.Nat,
    }),
    'wallet' : IDL.Null,
  });
  const Address = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const TrackingStep = IDL.Record({
    'status' : OrderStatus,
    'note' : IDL.Text,
    'timestamp' : IDL.Opt(Timestamp),
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'userId' : UserId,
    'discountAmount' : IDL.Nat,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'totalAmount' : IDL.Nat,
    'address' : Address,
    'couponApplied' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
    'trackingSteps' : IDL.Vec(TrackingStep),
  });
  const UserProfile = IDL.Record({
    'referralCode' : ReferralCode,
    'preferredLanguage' : IDL.Text,
    'name' : IDL.Text,
    'rewardPoints' : IDL.Nat,
    'email' : IDL.Text,
    'referredBy' : IDL.Opt(ReferralCode),
    'recentlyViewed' : IDL.Vec(ProductId),
    'address' : IDL.Opt(
      IDL.Record({
        'city' : IDL.Text,
        'line1' : IDL.Text,
        'line2' : IDL.Text,
        'state' : IDL.Text,
        'pincode' : IDL.Text,
      })
    ),
    'phone' : IDL.Text,
    'wishlist' : IDL.Vec(ProductId),
  });
  const Coupon = IDL.Record({
    'discountValue' : IDL.Nat,
    'expiresAt' : Timestamp,
    'maxDiscount' : IDL.Nat,
    'code' : CouponCode,
    'discountType' : DiscountType,
    'usageCount' : IDL.Nat,
    'maxUsage' : IDL.Nat,
    'minOrderValue' : IDL.Nat,
    'isActive' : IDL.Bool,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Cart = IDL.Record({
    'userId' : UserId,
    'couponApplied' : IDL.Opt(CouponCode),
    'items' : IDL.Vec(CartItem),
  });
  const NotificationId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'reward' : IDL.Null,
    'order' : IDL.Null,
    'deal' : IDL.Null,
    'price_drop' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'userId' : UserId,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
  });
  const PlaceOrderInput = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'discountAmount' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'address' : Address,
    'couponApplied' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
  });
  const UserProfileInput = IDL.Record({
    'preferredLanguage' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Opt(
      IDL.Record({
        'city' : IDL.Text,
        'line1' : IDL.Text,
        'line2' : IDL.Text,
        'state' : IDL.Text,
        'pincode' : IDL.Text,
      })
    ),
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBanner' : IDL.Func([BannerInput], [Banner], []),
    'addCoupon' : IDL.Func([CouponInput], [], []),
    'addProduct' : IDL.Func([ProductInput], [Product], []),
    'addReview' : IDL.Func([ReviewInput], [Review], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
    'applyCoupon' : IDL.Func([CouponCode, IDL.Nat], [ApplyCouponResult], []),
    'applyReferralCode' : IDL.Func([ReferralCode], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteBanner' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCoupon' : IDL.Func([CouponCode], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'deleteReview' : IDL.Func([ReviewId], [IDL.Bool], []),
    'generateReferralCode' : IDL.Func([], [ReferralCode], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserId, UserProfile))],
        ['query'],
      ),
    'getAvailableCoupons' : IDL.Func([IDL.Nat], [IDL.Vec(Coupon)], ['query']),
    'getBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
    'getBestCoupon' : IDL.Func([IDL.Nat], [IDL.Opt(Coupon)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFlashDeals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getRecentlyViewed' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'getReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
    'getRewards' : IDL.Func([], [IDL.Nat], ['query']),
    'getTrendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'placeOrder' : IDL.Func([PlaceOrderInput], [Order], []),
    'redeemRewards' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'removeFromWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileInput], [UserProfile], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'seedSampleData' : IDL.Func([], [IDL.Text], []),
    'sendNotification' : IDL.Func(
        [UserId, NotificationType, IDL.Text, IDL.Text],
        [Notification],
        [],
      ),
    'trackRecentlyViewed' : IDL.Func([ProductId], [], []),
    'updateBanner' : IDL.Func([IDL.Nat, BannerInput], [IDL.Opt(Banner)], []),
    'updateCartItem' : IDL.Func([ProductId, IDL.Nat], [], []),
    'updateCoupon' : IDL.Func([CouponInput], [IDL.Bool], []),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Opt(Order)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, ProductInput],
        [IDL.Opt(Product)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };