/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'city' : string,
  'name' : string,
  'line1' : string,
  'line2' : string,
  'state' : string,
  'phone' : string,
  'pincode' : string,
}
export interface ApplyCouponResult {
  'discountAmount' : bigint,
  'message' : string,
  'isValid' : boolean,
}
export interface Banner {
  'id' : bigint,
  'title' : string,
  'linkUrl' : string,
  'order' : bigint,
  'isActive' : boolean,
  'image' : ExternalBlob,
  'subtitle' : string,
}
export interface BannerInput {
  'title' : string,
  'linkUrl' : string,
  'order' : bigint,
  'isActive' : boolean,
  'image' : ExternalBlob,
  'subtitle' : string,
}
export interface Cart {
  'userId' : UserId,
  'couponApplied' : [] | [CouponCode],
  'items' : Array<CartItem>,
}
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export interface Coupon {
  'discountValue' : bigint,
  'expiresAt' : Timestamp,
  'maxDiscount' : bigint,
  'code' : CouponCode,
  'discountType' : DiscountType,
  'usageCount' : bigint,
  'maxUsage' : bigint,
  'minOrderValue' : bigint,
  'isActive' : boolean,
}
export type CouponCode = string;
export interface CouponInput {
  'discountValue' : bigint,
  'expiresAt' : Timestamp,
  'maxDiscount' : bigint,
  'code' : CouponCode,
  'discountType' : DiscountType,
  'maxUsage' : bigint,
  'minOrderValue' : bigint,
  'isActive' : boolean,
}
export type DiscountType = { 'flat' : null } |
  { 'percent' : null };
export type ExternalBlob = Uint8Array;
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'body' : string,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : boolean,
}
export type NotificationId = bigint;
export type NotificationType = { 'reward' : null } |
  { 'order' : null } |
  { 'deal' : null } |
  { 'price_drop' : null };
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'userId' : UserId,
  'discountAmount' : bigint,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalAmount' : bigint,
  'address' : Address,
  'couponApplied' : [] | [string],
  'items' : Array<OrderItem>,
  'trackingSteps' : Array<TrackingStep>,
}
export type OrderId = bigint;
export interface OrderItem {
  'name' : string,
  'productId' : ProductId,
  'quantity' : bigint,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'out_for_delivery' : null } |
  { 'ordered' : null } |
  { 'delivered' : null } |
  { 'packed' : null };
export type PaymentMethod = { 'cod' : null } |
  { 'upi' : null } |
  { 'card' : null } |
  {
    'split' : {
      'method1' : string,
      'method2' : string,
      'amount1' : bigint,
      'amount2' : bigint,
    }
  } |
  { 'wallet' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export interface PlaceOrderInput {
  'paymentMethod' : PaymentMethod,
  'discountAmount' : bigint,
  'totalAmount' : bigint,
  'address' : Address,
  'couponApplied' : [] | [string],
  'items' : Array<OrderItem>,
}
export interface Product {
  'id' : ProductId,
  'specifications' : Array<Specification>,
  'originalPrice' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'stock' : bigint,
  'category' : string,
  'rating' : number,
  'price' : bigint,
  'reviewCount' : bigint,
  'isFlashDeal' : boolean,
  'isTrending' : boolean,
  'images' : Array<ExternalBlob>,
}
export type ProductId = bigint;
export interface ProductInput {
  'specifications' : Array<Specification>,
  'originalPrice' : bigint,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'stock' : bigint,
  'category' : string,
  'price' : bigint,
  'isFlashDeal' : boolean,
  'isTrending' : boolean,
  'images' : Array<ExternalBlob>,
}
export type ReferralCode = string;
export interface Review {
  'id' : ReviewId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'comment' : string,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface ReviewInput {
  'productId' : ProductId,
  'comment' : string,
  'rating' : bigint,
}
export interface Specification { 'key' : string, 'value' : string }
export type Timestamp = bigint;
export interface TrackingStep {
  'status' : OrderStatus,
  'note' : string,
  'timestamp' : [] | [Timestamp],
}
export type UserId = Principal;
export interface UserProfile {
  'referralCode' : ReferralCode,
  'preferredLanguage' : string,
  'name' : string,
  'rewardPoints' : bigint,
  'email' : string,
  'referredBy' : [] | [ReferralCode],
  'recentlyViewed' : Array<ProductId>,
  'address' : [] | [
    {
      'city' : string,
      'line1' : string,
      'line2' : string,
      'state' : string,
      'pincode' : string,
    }
  ],
  'phone' : string,
  'wishlist' : Array<ProductId>,
}
export interface UserProfileInput {
  'preferredLanguage' : string,
  'name' : string,
  'email' : string,
  'address' : [] | [
    {
      'city' : string,
      'line1' : string,
      'line2' : string,
      'state' : string,
      'pincode' : string,
    }
  ],
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBanner' : ActorMethod<[BannerInput], Banner>,
  'addCoupon' : ActorMethod<[CouponInput], undefined>,
  'addProduct' : ActorMethod<[ProductInput], Product>,
  'addReview' : ActorMethod<[ReviewInput], Review>,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'addToWishlist' : ActorMethod<[ProductId], boolean>,
  'applyCoupon' : ActorMethod<[CouponCode, bigint], ApplyCouponResult>,
  'applyReferralCode' : ActorMethod<[ReferralCode], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'deleteBanner' : ActorMethod<[bigint], boolean>,
  'deleteCoupon' : ActorMethod<[CouponCode], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'deleteReview' : ActorMethod<[ReviewId], boolean>,
  'generateReferralCode' : ActorMethod<[], ReferralCode>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllUsers' : ActorMethod<[], Array<[UserId, UserProfile]>>,
  'getAvailableCoupons' : ActorMethod<[bigint], Array<Coupon>>,
  'getBanners' : ActorMethod<[], Array<Banner>>,
  'getBestCoupon' : ActorMethod<[bigint], [] | [Coupon]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getFlashDeals' : ActorMethod<[], Array<Product>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyReviews' : ActorMethod<[], Array<Review>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getRecentlyViewed' : ActorMethod<[], Array<ProductId>>,
  'getReviews' : ActorMethod<[ProductId], Array<Review>>,
  'getRewards' : ActorMethod<[], bigint>,
  'getTrendingProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<ProductId>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationRead' : ActorMethod<[NotificationId], boolean>,
  'placeOrder' : ActorMethod<[PlaceOrderInput], Order>,
  'redeemRewards' : ActorMethod<[bigint], boolean>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'removeFromWishlist' : ActorMethod<[ProductId], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileInput], UserProfile>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'seedSampleData' : ActorMethod<[], string>,
  'sendNotification' : ActorMethod<
    [UserId, NotificationType, string, string],
    Notification
  >,
  'trackRecentlyViewed' : ActorMethod<[ProductId], undefined>,
  'updateBanner' : ActorMethod<[bigint, BannerInput], [] | [Banner]>,
  'updateCartItem' : ActorMethod<[ProductId, bigint], undefined>,
  'updateCoupon' : ActorMethod<[CouponInput], boolean>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [Order]>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], [] | [Product]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];