/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type OrderId = bigint;
export interface UserProfileInput {
    preferredLanguage: string;
    name: string;
    email: string;
    address?: {
        city: string;
        line1: string;
        line2: string;
        state: string;
        pincode: string;
    };
    phone: string;
}
export type Timestamp = bigint;
export interface CouponInput {
    discountValue: bigint;
    expiresAt: Timestamp;
    maxDiscount: bigint;
    code: CouponCode;
    discountType: DiscountType;
    maxUsage: bigint;
    minOrderValue: bigint;
    isActive: boolean;
}
export interface CartItem {
    productId: ProductId;
    quantity: bigint;
}
export type PaymentMethod = {
    __kind__: "cod";
    cod: null;
} | {
    __kind__: "upi";
    upi: null;
} | {
    __kind__: "card";
    card: null;
} | {
    __kind__: "split";
    split: {
        method1: string;
        method2: string;
        amount1: bigint;
        amount2: bigint;
    };
} | {
    __kind__: "wallet";
    wallet: null;
};
export interface Address {
    city: string;
    name: string;
    line1: string;
    line2: string;
    state: string;
    phone: string;
    pincode: string;
}
export interface OrderItem {
    name: string;
    productId: ProductId;
    quantity: bigint;
    image: ExternalBlob;
    price: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ApplyCouponResult {
    discountAmount: bigint;
    message: string;
    isValid: boolean;
}
export type CouponCode = string;
export interface Cart {
    userId: UserId;
    couponApplied?: CouponCode;
    items: Array<CartItem>;
}
export type ReviewId = bigint;
export interface BannerInput {
    title: string;
    linkUrl: string;
    order: bigint;
    isActive: boolean;
    image: ExternalBlob;
    subtitle: string;
}
export interface Specification {
    key: string;
    value: string;
}
export interface Review {
    id: ReviewId;
    userId: UserId;
    createdAt: Timestamp;
    productId: ProductId;
    comment: string;
    rating: bigint;
}
export interface ProductInput {
    specifications: Array<Specification>;
    originalPrice: bigint;
    name: string;
    tags: Array<string>;
    description: string;
    stock: bigint;
    category: string;
    price: bigint;
    isFlashDeal: boolean;
    isTrending: boolean;
    images: Array<ExternalBlob>;
}
export interface PlaceOrderInput {
    paymentMethod: PaymentMethod;
    discountAmount: bigint;
    totalAmount: bigint;
    address: Address;
    couponApplied?: string;
    items: Array<OrderItem>;
}
export interface Coupon {
    discountValue: bigint;
    expiresAt: Timestamp;
    maxDiscount: bigint;
    code: CouponCode;
    discountType: DiscountType;
    usageCount: bigint;
    maxUsage: bigint;
    minOrderValue: bigint;
    isActive: boolean;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    paymentStatus: PaymentStatus;
    paymentMethod: PaymentMethod;
    userId: UserId;
    discountAmount: bigint;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    totalAmount: bigint;
    address: Address;
    couponApplied?: string;
    items: Array<OrderItem>;
    trackingSteps: Array<TrackingStep>;
}
export type UserId = Principal;
export interface Banner {
    id: bigint;
    title: string;
    linkUrl: string;
    order: bigint;
    isActive: boolean;
    image: ExternalBlob;
    subtitle: string;
}
export type NotificationId = bigint;
export interface Notification {
    id: NotificationId;
    title: string;
    body: string;
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    isRead: boolean;
}
export interface TrackingStep {
    status: OrderStatus;
    note: string;
    timestamp?: Timestamp;
}
export type ProductId = bigint;
export type ReferralCode = string;
export interface ReviewInput {
    productId: ProductId;
    comment: string;
    rating: bigint;
}
export interface UserProfile {
    referralCode: ReferralCode;
    preferredLanguage: string;
    name: string;
    rewardPoints: bigint;
    email: string;
    referredBy?: ReferralCode;
    recentlyViewed: Array<ProductId>;
    address?: {
        city: string;
        line1: string;
        line2: string;
        state: string;
        pincode: string;
    };
    phone: string;
    wishlist: Array<ProductId>;
}
export interface Product {
    id: ProductId;
    specifications: Array<Specification>;
    originalPrice: bigint;
    name: string;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    stock: bigint;
    category: string;
    rating: number;
    price: bigint;
    reviewCount: bigint;
    isFlashDeal: boolean;
    isTrending: boolean;
    images: Array<ExternalBlob>;
}
export enum DiscountType {
    flat = "flat",
    percent = "percent"
}
export enum NotificationType {
    reward = "reward",
    order = "order",
    deal = "deal",
    price_drop = "price_drop"
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    out_for_delivery = "out_for_delivery",
    ordered = "ordered",
    delivered = "delivered",
    packed = "packed"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    refunded = "refunded",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addBanner(input: BannerInput): Promise<Banner>;
    addCoupon(input: CouponInput): Promise<void>;
    addProduct(input: ProductInput): Promise<Product>;
    addReview(input: ReviewInput): Promise<Review>;
    addToCart(productId: ProductId, quantity: bigint): Promise<void>;
    addToWishlist(productId: ProductId): Promise<boolean>;
    applyCoupon(code: CouponCode, orderTotal: bigint): Promise<ApplyCouponResult>;
    applyReferralCode(code: ReferralCode): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCart(): Promise<void>;
    deleteBanner(id: bigint): Promise<boolean>;
    deleteCoupon(code: CouponCode): Promise<boolean>;
    deleteProduct(id: ProductId): Promise<boolean>;
    deleteReview(reviewId: ReviewId): Promise<boolean>;
    generateReferralCode(): Promise<ReferralCode>;
    getAllOrders(): Promise<Array<Order>>;
    getAllUsers(): Promise<Array<[UserId, UserProfile]>>;
    getAvailableCoupons(orderTotal: bigint): Promise<Array<Coupon>>;
    getBanners(): Promise<Array<Banner>>;
    getBestCoupon(orderTotal: bigint): Promise<Coupon | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<Cart>;
    getCategories(): Promise<Array<string>>;
    getFlashDeals(): Promise<Array<Product>>;
    getMyOrders(): Promise<Array<Order>>;
    getMyReviews(): Promise<Array<Review>>;
    getNotifications(): Promise<Array<Notification>>;
    getOrder(orderId: OrderId): Promise<Order | null>;
    getProduct(id: ProductId): Promise<Product | null>;
    getProducts(): Promise<Array<Product>>;
    getProductsByCategory(category: string): Promise<Array<Product>>;
    getRecentlyViewed(): Promise<Array<ProductId>>;
    getReviews(productId: ProductId): Promise<Array<Review>>;
    getRewards(): Promise<bigint>;
    getTrendingProducts(): Promise<Array<Product>>;
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    getWishlist(): Promise<Array<ProductId>>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationRead(notificationId: NotificationId): Promise<boolean>;
    placeOrder(input: PlaceOrderInput): Promise<Order>;
    redeemRewards(points: bigint): Promise<boolean>;
    removeFromCart(productId: ProductId): Promise<void>;
    removeFromWishlist(productId: ProductId): Promise<boolean>;
    saveCallerUserProfile(input: UserProfileInput): Promise<UserProfile>;
    searchProducts(searchQuery: string): Promise<Array<Product>>;
    seedSampleData(): Promise<string>;
    sendNotification(userId: UserId, notificationType: NotificationType, title: string, body: string): Promise<Notification>;
    trackRecentlyViewed(productId: ProductId): Promise<void>;
    updateBanner(id: bigint, input: BannerInput): Promise<Banner | null>;
    updateCartItem(productId: ProductId, quantity: bigint): Promise<void>;
    updateCoupon(input: CouponInput): Promise<boolean>;
    updateOrderStatus(orderId: OrderId, newStatus: OrderStatus): Promise<Order | null>;
    updateProduct(id: ProductId, input: ProductInput): Promise<Product | null>;
}
import type { Address as _Address, Banner as _Banner, BannerInput as _BannerInput, Cart as _Cart, CartItem as _CartItem, Coupon as _Coupon, CouponCode as _CouponCode, CouponInput as _CouponInput, DiscountType as _DiscountType, ExternalBlob as _ExternalBlob, Notification as _Notification, NotificationId as _NotificationId, NotificationType as _NotificationType, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, PlaceOrderInput as _PlaceOrderInput, Product as _Product, ProductId as _ProductId, ProductInput as _ProductInput, ReferralCode as _ReferralCode, Specification as _Specification, Timestamp as _Timestamp, TrackingStep as _TrackingStep, UserId as _UserId, UserProfile as _UserProfile, UserProfileInput as _UserProfileInput, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addBanner(arg0: BannerInput): Promise<Banner> {
        if (this.processError) {
            try {
                const result = await this.actor.addBanner(await to_candid_BannerInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Banner_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBanner(await to_candid_BannerInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Banner_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async addCoupon(arg0: CouponInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoupon(to_candid_CouponInput_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoupon(to_candid_CouponInput_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProduct(arg0: ProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(await to_candid_ProductInput_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(await to_candid_ProductInput_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async addReview(arg0: ReviewInput): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return result;
        }
    }
    async addToCart(arg0: ProductId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async addToWishlist(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async applyCoupon(arg0: CouponCode, arg1: bigint): Promise<ApplyCouponResult> {
        if (this.processError) {
            try {
                const result = await this.actor.applyCoupon(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyCoupon(arg0, arg1);
            return result;
        }
    }
    async applyReferralCode(arg0: ReferralCode): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.applyReferralCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyReferralCode(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async deleteBanner(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBanner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBanner(arg0);
            return result;
        }
    }
    async deleteCoupon(arg0: CouponCode): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoupon(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteReview(arg0: ReviewId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async generateReferralCode(): Promise<ReferralCode> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReferralCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReferralCode();
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<[UserId, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableCoupons(arg0: bigint): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableCoupons(arg0);
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableCoupons(arg0);
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBanners(): Promise<Array<Banner>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBanners();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBanners();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBestCoupon(arg0: bigint): Promise<Coupon | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBestCoupon(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBestCoupon(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return from_candid_Cart_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return from_candid_Cart_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getFlashDeals(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlashDeals();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlashDeals();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReviews();
            return result;
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(arg0);
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(arg0);
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentlyViewed(): Promise<Array<ProductId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentlyViewed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentlyViewed();
            return result;
        }
    }
    async getReviews(arg0: ProductId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews(arg0);
            return result;
        }
    }
    async getRewards(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewards();
            return result;
        }
    }
    async getTrendingProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingProducts();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingProducts();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWishlist(): Promise<Array<ProductId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationRead(arg0: NotificationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async placeOrder(arg0: PlaceOrderInput): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(await to_candid_PlaceOrderInput_n70(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(await to_candid_PlaceOrderInput_n70(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async redeemRewards(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemRewards(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemRewards(arg0);
            return result;
        }
    }
    async removeFromCart(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async removeFromWishlist(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileInput): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileInput_n77(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfile_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileInput_n77(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfile_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedSampleData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async sendNotification(arg0: UserId, arg1: NotificationType, arg2: string, arg3: string): Promise<Notification> {
        if (this.processError) {
            try {
                const result = await this.actor.sendNotification(arg0, to_candid_NotificationType_n79(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_Notification_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendNotification(arg0, to_candid_NotificationType_n79(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_Notification_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async trackRecentlyViewed(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackRecentlyViewed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackRecentlyViewed(arg0);
            return result;
        }
    }
    async updateBanner(arg0: bigint, arg1: BannerInput): Promise<Banner | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBanner(arg0, await to_candid_BannerInput_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBanner(arg0, await to_candid_BannerInput_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCartItem(arg0: ProductId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItem(arg0, arg1);
            return result;
        }
    }
    async updateCoupon(arg0: CouponInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoupon(to_candid_CouponInput_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoupon(to_candid_CouponInput_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n82(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n82(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: ProductId, arg1: ProductInput): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, await to_candid_ProductInput_n18(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, await to_candid_ProductInput_n18(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n69(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_Banner_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Banner): Promise<Banner> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Cart_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cart): Cart {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_Coupon_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Coupon): Coupon {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_DiscountType_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscountType): DiscountType {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_NotificationType_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n65(_uploadFile, _downloadFile, value);
}
async function from_candid_OrderItem_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderItem): Promise<OrderItem> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_Order_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Promise<Order> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_TrackingStep_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrackingStep): TrackingStep {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReferralCode]): ReferralCode | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        city: string;
        line1: string;
        line2: string;
        state: string;
        pincode: string;
    }]): {
    city: string;
    line1: string;
    line2: string;
    state: string;
    pincode: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coupon]): Coupon | null {
    return value.length === 0 ? null : from_candid_Coupon_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CouponCode]): CouponCode | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Promise<Order | null> {
    return value.length === 0 ? null : await from_candid_Order_n27(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Promise<Product | null> {
    return value.length === 0 ? null : await from_candid_Product_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Banner]): Promise<Banner | null> {
    return value.length === 0 ? null : await from_candid_Banner_n11(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    linkUrl: string;
    order: bigint;
    isActive: boolean;
    image: _ExternalBlob;
    subtitle: string;
}): Promise<{
    id: bigint;
    title: string;
    linkUrl: string;
    order: bigint;
    isActive: boolean;
    image: ExternalBlob;
    subtitle: string;
}> {
    return {
        id: value.id,
        title: value.title,
        linkUrl: value.linkUrl,
        order: value.order,
        isActive: value.isActive,
        image: await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.image),
        subtitle: value.subtitle
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    specifications: Array<_Specification>;
    originalPrice: bigint;
    name: string;
    createdAt: _Timestamp;
    tags: Array<string>;
    description: string;
    stock: bigint;
    category: string;
    rating: number;
    price: bigint;
    reviewCount: bigint;
    isFlashDeal: boolean;
    isTrending: boolean;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: ProductId;
    specifications: Array<Specification>;
    originalPrice: bigint;
    name: string;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    stock: bigint;
    category: string;
    rating: number;
    price: bigint;
    reviewCount: bigint;
    isFlashDeal: boolean;
    isTrending: boolean;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        specifications: value.specifications,
        originalPrice: value.originalPrice,
        name: value.name,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        stock: value.stock,
        category: value.category,
        rating: value.rating,
        price: value.price,
        reviewCount: value.reviewCount,
        isFlashDeal: value.isFlashDeal,
        isTrending: value.isTrending,
        images: await from_candid_vec_n23(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    paymentStatus: _PaymentStatus;
    paymentMethod: _PaymentMethod;
    userId: _UserId;
    discountAmount: bigint;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    totalAmount: bigint;
    address: _Address;
    couponApplied: [] | [string];
    items: Array<_OrderItem>;
    trackingSteps: Array<_TrackingStep>;
}): Promise<{
    id: OrderId;
    status: OrderStatus;
    paymentStatus: PaymentStatus;
    paymentMethod: PaymentMethod;
    userId: UserId;
    discountAmount: bigint;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    totalAmount: bigint;
    address: Address;
    couponApplied?: string;
    items: Array<OrderItem>;
    trackingSteps: Array<TrackingStep>;
}> {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n29(_uploadFile, _downloadFile, value.status),
        paymentStatus: from_candid_PaymentStatus_n31(_uploadFile, _downloadFile, value.paymentStatus),
        paymentMethod: from_candid_PaymentMethod_n33(_uploadFile, _downloadFile, value.paymentMethod),
        userId: value.userId,
        discountAmount: value.discountAmount,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        totalAmount: value.totalAmount,
        address: value.address,
        couponApplied: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.couponApplied)),
        items: await from_candid_vec_n36(_uploadFile, _downloadFile, value.items),
        trackingSteps: from_candid_vec_n39(_uploadFile, _downloadFile, value.trackingSteps)
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    productId: _ProductId;
    quantity: bigint;
    image: _ExternalBlob;
    price: bigint;
}): Promise<{
    name: string;
    productId: ProductId;
    quantity: bigint;
    image: ExternalBlob;
    price: bigint;
}> {
    return {
        name: value.name,
        productId: value.productId,
        quantity: value.quantity,
        image: await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrderStatus;
    note: string;
    timestamp: [] | [_Timestamp];
}): {
    status: OrderStatus;
    note: string;
    timestamp?: Timestamp;
} {
    return {
        status: from_candid_OrderStatus_n29(_uploadFile, _downloadFile, value.status),
        note: value.note,
        timestamp: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.timestamp))
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: _ReferralCode;
    preferredLanguage: string;
    name: string;
    rewardPoints: bigint;
    email: string;
    referredBy: [] | [_ReferralCode];
    recentlyViewed: Array<_ProductId>;
    address: [] | [{
            city: string;
            line1: string;
            line2: string;
            state: string;
            pincode: string;
        }];
    phone: string;
    wishlist: Array<_ProductId>;
}): {
    referralCode: ReferralCode;
    preferredLanguage: string;
    name: string;
    rewardPoints: bigint;
    email: string;
    referredBy?: ReferralCode;
    recentlyViewed: Array<ProductId>;
    address?: {
        city: string;
        line1: string;
        line2: string;
        state: string;
        pincode: string;
    };
    phone: string;
    wishlist: Array<ProductId>;
} {
    return {
        referralCode: value.referralCode,
        preferredLanguage: value.preferredLanguage,
        name: value.name,
        rewardPoints: value.rewardPoints,
        email: value.email,
        referredBy: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.referredBy)),
        recentlyViewed: value.recentlyViewed,
        address: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.address)),
        phone: value.phone,
        wishlist: value.wishlist
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    discountValue: bigint;
    expiresAt: _Timestamp;
    maxDiscount: bigint;
    code: _CouponCode;
    discountType: _DiscountType;
    usageCount: bigint;
    maxUsage: bigint;
    minOrderValue: bigint;
    isActive: boolean;
}): {
    discountValue: bigint;
    expiresAt: Timestamp;
    maxDiscount: bigint;
    code: CouponCode;
    discountType: DiscountType;
    usageCount: bigint;
    maxUsage: bigint;
    minOrderValue: bigint;
    isActive: boolean;
} {
    return {
        discountValue: value.discountValue,
        expiresAt: value.expiresAt,
        maxDiscount: value.maxDiscount,
        code: value.code,
        discountType: from_candid_DiscountType_n52(_uploadFile, _downloadFile, value.discountType),
        usageCount: value.usageCount,
        maxUsage: value.maxUsage,
        minOrderValue: value.minOrderValue,
        isActive: value.isActive
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    couponApplied: [] | [_CouponCode];
    items: Array<_CartItem>;
}): {
    userId: UserId;
    couponApplied?: CouponCode;
    items: Array<CartItem>;
} {
    return {
        userId: value.userId,
        couponApplied: record_opt_to_undefined(from_candid_opt_n61(_uploadFile, _downloadFile, value.couponApplied)),
        items: value.items
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    title: string;
    body: string;
    userId: _UserId;
    notificationType: _NotificationType;
    createdAt: _Timestamp;
    isRead: boolean;
}): {
    id: NotificationId;
    title: string;
    body: string;
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    isRead: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        userId: value.userId,
        notificationType: from_candid_NotificationType_n66(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        isRead: value.isRead
    };
}
function from_candid_tuple_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_UserId, _UserProfile]): [UserId, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n45(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    out_for_delivery: null;
} | {
    ordered: null;
} | {
    delivered: null;
} | {
    packed: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "out_for_delivery" in value ? OrderStatus.out_for_delivery : "ordered" in value ? OrderStatus.ordered : "delivered" in value ? OrderStatus.delivered : "packed" in value ? OrderStatus.packed : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "refunded" in value ? PaymentStatus.refunded : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cod: null;
} | {
    upi: null;
} | {
    card: null;
} | {
    split: {
        method1: string;
        method2: string;
        amount1: bigint;
        amount2: bigint;
    };
} | {
    wallet: null;
}): {
    __kind__: "cod";
    cod: null;
} | {
    __kind__: "upi";
    upi: null;
} | {
    __kind__: "card";
    card: null;
} | {
    __kind__: "split";
    split: {
        method1: string;
        method2: string;
        amount1: bigint;
        amount2: bigint;
    };
} | {
    __kind__: "wallet";
    wallet: null;
} {
    return "cod" in value ? {
        __kind__: "cod",
        cod: value.cod
    } : "upi" in value ? {
        __kind__: "upi",
        upi: value.upi
    } : "card" in value ? {
        __kind__: "card",
        card: value.card
    } : "split" in value ? {
        __kind__: "split",
        split: value.split
    } : "wallet" in value ? {
        __kind__: "wallet",
        wallet: value.wallet
    } : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flat: null;
} | {
    percent: null;
}): DiscountType {
    return "flat" in value ? DiscountType.flat : "percent" in value ? DiscountType.percent : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reward: null;
} | {
    order: null;
} | {
    deal: null;
} | {
    price_drop: null;
}): NotificationType {
    return "reward" in value ? NotificationType.reward : "order" in value ? NotificationType.order : "deal" in value ? NotificationType.deal : "price_drop" in value ? NotificationType.price_drop : value;
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Promise<Array<Order>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Order_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderItem>): Promise<Array<OrderItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_OrderItem_n37(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrackingStep>): Array<TrackingStep> {
    return value.map((x)=>from_candid_TrackingStep_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_UserId, _UserProfile]>): Array<[UserId, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Coupon>): Array<Coupon> {
    return value.map((x)=>from_candid_Coupon_n50(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Banner>): Promise<Array<Banner>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Banner_n11(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n21(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n64(_uploadFile, _downloadFile, x));
}
async function to_candid_BannerInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BannerInput): Promise<_BannerInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_CouponInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CouponInput): _CouponInput {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_DiscountType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): _DiscountType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_NotificationType_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): _NotificationType {
    return to_candid_variant_n80(_uploadFile, _downloadFile, value);
}
async function to_candid_OrderItem_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderItem): Promise<_OrderItem> {
    return await to_candid_record_n76(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n83(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n73(_uploadFile, _downloadFile, value);
}
async function to_candid_PlaceOrderInput_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceOrderInput): Promise<_PlaceOrderInput> {
    return await to_candid_record_n71(_uploadFile, _downloadFile, value);
}
async function to_candid_ProductInput_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): Promise<_ProductInput> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfileInput_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileInput): _UserProfileInput {
    return to_candid_record_n78(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    discountValue: bigint;
    expiresAt: Timestamp;
    maxDiscount: bigint;
    code: CouponCode;
    discountType: DiscountType;
    maxUsage: bigint;
    minOrderValue: bigint;
    isActive: boolean;
}): {
    discountValue: bigint;
    expiresAt: _Timestamp;
    maxDiscount: bigint;
    code: _CouponCode;
    discountType: _DiscountType;
    maxUsage: bigint;
    minOrderValue: bigint;
    isActive: boolean;
} {
    return {
        discountValue: value.discountValue,
        expiresAt: value.expiresAt,
        maxDiscount: value.maxDiscount,
        code: value.code,
        discountType: to_candid_DiscountType_n16(_uploadFile, _downloadFile, value.discountType),
        maxUsage: value.maxUsage,
        minOrderValue: value.minOrderValue,
        isActive: value.isActive
    };
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    specifications: Array<Specification>;
    originalPrice: bigint;
    name: string;
    tags: Array<string>;
    description: string;
    stock: bigint;
    category: string;
    price: bigint;
    isFlashDeal: boolean;
    isTrending: boolean;
    images: Array<ExternalBlob>;
}): Promise<{
    specifications: Array<_Specification>;
    originalPrice: bigint;
    name: string;
    tags: Array<string>;
    description: string;
    stock: bigint;
    category: string;
    price: bigint;
    isFlashDeal: boolean;
    isTrending: boolean;
    images: Array<_ExternalBlob>;
}> {
    return {
        specifications: value.specifications,
        originalPrice: value.originalPrice,
        name: value.name,
        tags: value.tags,
        description: value.description,
        stock: value.stock,
        category: value.category,
        price: value.price,
        isFlashDeal: value.isFlashDeal,
        isTrending: value.isTrending,
        images: await to_candid_vec_n20(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: PaymentMethod;
    discountAmount: bigint;
    totalAmount: bigint;
    address: Address;
    couponApplied?: string;
    items: Array<OrderItem>;
}): Promise<{
    paymentMethod: _PaymentMethod;
    discountAmount: bigint;
    totalAmount: bigint;
    address: _Address;
    couponApplied: [] | [string];
    items: Array<_OrderItem>;
}> {
    return {
        paymentMethod: to_candid_PaymentMethod_n72(_uploadFile, _downloadFile, value.paymentMethod),
        discountAmount: value.discountAmount,
        totalAmount: value.totalAmount,
        address: value.address,
        couponApplied: value.couponApplied ? candid_some(value.couponApplied) : candid_none(),
        items: await to_candid_vec_n74(_uploadFile, _downloadFile, value.items)
    };
}
async function to_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    productId: ProductId;
    quantity: bigint;
    image: ExternalBlob;
    price: bigint;
}): Promise<{
    name: string;
    productId: _ProductId;
    quantity: bigint;
    image: _ExternalBlob;
    price: bigint;
}> {
    return {
        name: value.name,
        productId: value.productId,
        quantity: value.quantity,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
function to_candid_record_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferredLanguage: string;
    name: string;
    email: string;
    address?: {
        city: string;
        line1: string;
        line2: string;
        state: string;
        pincode: string;
    };
    phone: string;
}): {
    preferredLanguage: string;
    name: string;
    email: string;
    address: [] | [{
            city: string;
            line1: string;
            line2: string;
            state: string;
            pincode: string;
        }];
    phone: string;
} {
    return {
        preferredLanguage: value.preferredLanguage,
        name: value.name,
        email: value.email,
        address: value.address ? candid_some(value.address) : candid_none(),
        phone: value.phone
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    linkUrl: string;
    order: bigint;
    isActive: boolean;
    image: ExternalBlob;
    subtitle: string;
}): Promise<{
    title: string;
    linkUrl: string;
    order: bigint;
    isActive: boolean;
    image: _ExternalBlob;
    subtitle: string;
}> {
    return {
        title: value.title,
        linkUrl: value.linkUrl,
        order: value.order,
        isActive: value.isActive,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image),
        subtitle: value.subtitle
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): {
    flat: null;
} | {
    percent: null;
} {
    return value == DiscountType.flat ? {
        flat: null
    } : value == DiscountType.percent ? {
        percent: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "cod";
    cod: null;
} | {
    __kind__: "upi";
    upi: null;
} | {
    __kind__: "card";
    card: null;
} | {
    __kind__: "split";
    split: {
        method1: string;
        method2: string;
        amount1: bigint;
        amount2: bigint;
    };
} | {
    __kind__: "wallet";
    wallet: null;
}): {
    cod: null;
} | {
    upi: null;
} | {
    card: null;
} | {
    split: {
        method1: string;
        method2: string;
        amount1: bigint;
        amount2: bigint;
    };
} | {
    wallet: null;
} {
    return value.__kind__ === "cod" ? {
        cod: value.cod
    } : value.__kind__ === "upi" ? {
        upi: value.upi
    } : value.__kind__ === "card" ? {
        card: value.card
    } : value.__kind__ === "split" ? {
        split: value.split
    } : value.__kind__ === "wallet" ? {
        wallet: value.wallet
    } : value;
}
function to_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): {
    reward: null;
} | {
    order: null;
} | {
    deal: null;
} | {
    price_drop: null;
} {
    return value == NotificationType.reward ? {
        reward: null
    } : value == NotificationType.order ? {
        order: null
    } : value == NotificationType.deal ? {
        deal: null
    } : value == NotificationType.price_drop ? {
        price_drop: null
    } : value;
}
function to_candid_variant_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    out_for_delivery: null;
} | {
    ordered: null;
} | {
    delivered: null;
} | {
    packed: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.out_for_delivery ? {
        out_for_delivery: null
    } : value == OrderStatus.ordered ? {
        ordered: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.packed ? {
        packed: null
    } : value;
}
async function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OrderItem>): Promise<Array<_OrderItem>> {
    return await Promise.all(value.map(async (x)=>await to_candid_OrderItem_n75(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
